name: CI tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build
      - run: npm run build:runner
      - run: |
          node test-runner/dist/runtests.js -a -N --reporter spec 2>&1 | tee test-output.txt
          if grep -qE '[0-9]+ failing' test-output.txt; then
            exit 1
          fi
